<a href="https://colab.research.google.com/github/sbogde/pandamonium/blob/main/dmi_00_numpy_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arrays vs Lists

In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L:
  print(e)

1
2
3


In [5]:
for e in A:
  print(e)

1
2
3


In [6]:
L.append(4)

In [7]:
L

[1, 2, 3, 4]

In [8]:
# A.append(4) # doesn't work

In [9]:
# A = np.append(A, 5)
# A

In [10]:
L + [5]

[1, 2, 3, 4, 5]

In [11]:
A + np.array([4]) # the same as A + np.array([4, 4, 4])

array([5, 6, 7])

In [12]:
A + np.array([4,5,6])

array([5, 7, 9])

In [13]:
A + np.array([4,5]) # doesn't work

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
2 * A

In [ ]:
2 * L

In [ ]:
L + L

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)

In [ ]:
L2

In [ ]:
L2 = [e + 3 for e in L]

In [ ]:
L2

In [ ]:
L2 = []
for e in L:
  L2.append(e**2)

In [ ]:
L2

In [ ]:
A**2

In [ ]:
np.sqrt(A)

In [ ]:
np.log(A)

In [ ]:
np.exp(A)

In [ ]:
np.tanh(A)

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [14]:
a = np.array([1,2])
b = np.array([3,4])

In [15]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

11

In [16]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

11

In [17]:
a * b

array([3, 8])

In [18]:
np.sum(a * b)

11

In [19]:
(a * b).sum()

11

In [20]:
np.dot(a, b)

11

In [21]:
a.dot(b)

11

In [22]:
b.dot(a)

11

In [23]:
a @ b

11

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [24]:
amag = np.sqrt((a * a).sum())
amag

2.23606797749979

In [25]:
amag = np.linalg.norm(amag)
amag

2.23606797749979

In [26]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [27]:
cosangle

0.9838699100999074

In [28]:
angle = np.arccos(cosangle)
angle

0.17985349979247847

## Speed Test

In [32]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 54.0816793680038


## Matrices

In [ ]:
L = [[1,2], [3,4]]
L

In [ ]:
L[0]

In [ ]:
L[0][1]

In [ ]:
A = np.array([[1,2], [3,4]])
A

In [ ]:
A[0][1]

In [ ]:
A[0,1]

In [ ]:
A[:,0]

In [ ]:
A.T

In [ ]:
np.exp(A)

In [ ]:
np.exp(L)

In [ ]:
B = np.array([[1,2,3],[4,5,6]])
B

In [ ]:
A.dot(B)

In [ ]:
# error! inner dimensions must match
A.dot(B.T)

In [ ]:
np.linalg.det(A)

In [ ]:
np.linalg.inv(A)

In [ ]:
np.linalg.inv(A).dot(A)

In [ ]:
np.trace(A)

In [ ]:
np.diag(A)

In [ ]:
np.diag([1, 4])

In [ ]:
np.linalg.eig(A)

In [ ]:
Lam, V = np.linalg.eig(A)

In [ ]:
V[:,0] * Lam[0] == A @ V[:,0]

In [ ]:
V[:,0] * Lam[0], A @ V[:,0]

In [ ]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

In [ ]:
np.allclose(V @ np.diag(Lam), A @ V)

## Solving Linear Systems

In [ ]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [ ]:
np.linalg.solve(A, b)

In [ ]:
# don't do this
np.linalg.inv(A).dot(b)

## Generating Data

In [ ]:
np.zeros((2, 3))

In [ ]:
np.ones((2, 3))

In [ ]:
10 * np.ones((2, 3))

In [ ]:
np.eye(3)

In [ ]:
np.random.random()

In [ ]:
np.random.random((2, 3))

In [ ]:
np.random.randn(2, 3)

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

In [ ]:
np.mean(R)

In [ ]:
R.var()

In [ ]:
R = np.random.randn(10000, 3)

In [ ]:
R.mean(axis=0)

In [ ]:
R.mean(axis=1).shape

In [ ]:
np.cov(R).shape

In [ ]:
np.cov(R.T)

In [ ]:
np.cov(R, rowvar=False)

In [ ]:
np.random.randint(0, 10, size=(3, 3))

In [ ]:
np.random.choice(10, size=(3, 3))