<a href="https://colab.research.google.com/github/sbogde/pandamonium/blob/main/dmi_00_numpy_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Arrays vs Lists

In [84]:
import numpy as np

In [85]:
L = [1,2,3]

In [86]:
A = np.array([1,2,3])

In [87]:
for e in L:
  print(e)

1
2
3


In [88]:
for e in A:
  print(e)

1
2
3


In [89]:
L.append(4)

In [90]:
L

[1, 2, 3, 4]

In [91]:
# A.append(4) # doesn't work

In [92]:
# A = np.append(A, 5)
# A

In [93]:
L + [5]

[1, 2, 3, 4, 5]

In [94]:
A + np.array([4]) # the same as A + np.array([4, 4, 4])

array([5, 6, 7])

In [95]:
A + np.array([4,5,6])

array([5, 7, 9])

In [96]:
A + np.array([4,5]) # doesn't work

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
2 * A

In [ ]:
2 * L

In [ ]:
L + L

In [ ]:
L2 = []
for e in L:
  L2.append(e + 3)

In [ ]:
L2

In [ ]:
L2 = [e + 3 for e in L]

In [ ]:
L2

In [ ]:
L2 = []
for e in L:
  L2.append(e**2)

In [ ]:
L2

In [ ]:
A**2

In [ ]:
np.sqrt(A)

In [ ]:
np.log(A)

In [ ]:
np.exp(A)

In [ ]:
np.tanh(A)

## The Dot Product

$$ a \cdot b = a^T b = \sum_{d=1}^D a_d b_d $$

In [ ]:
a = np.array([1,2])
b = np.array([3,4])

In [ ]:
dot = 0
for e, f in zip(a, b):
  dot += e*f
dot

In [ ]:
# use integer index
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

In [ ]:
a * b

In [ ]:
np.sum(a * b)

In [ ]:
(a * b).sum()

In [97]:
np.dot(a, b)

NameError: name 'a' is not defined

In [ ]:
a.dot(b)

In [ ]:
b.dot(a)

In [ ]:
a @ b

$$ a^T b = \left\lVert a \right\rVert \left\lVert b \right\rVert \cos \theta_{ab}$$

$$ \cos \theta_{ab} = \frac{a^T b}{\left\lVert a \right\rVert \left\lVert b \right\rVert} $$

$$ \left\lVert a \right\rVert = \sqrt{\sum_{d=1}^D a_d^2 } $$

In [ ]:
amag = np.sqrt((a * a).sum())
amag

In [ ]:
amag = np.linalg.norm(amag)
amag

In [ ]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [98]:
cosangle

NameError: name 'cosangle' is not defined

In [ ]:
angle = np.arccos(cosangle)
angle

## Speed Test

In [99]:
## speed comparison ##
import numpy as np
from datetime import datetime

# note: you can also use %timeit

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

dt1 / dt2: 31.545378424315132


## Matrices

In [100]:
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [101]:
L[0]

[1, 2]

In [102]:
L[0][1]

2

In [103]:
A = np.array([[1,2], [3,4]])
A

array([[1, 2],
       [3, 4]])

In [104]:
A[0][1]

2

In [105]:
A[0,1]

2

In [106]:
A[:,0]

array([1, 3])

In [107]:
A.T

array([[1, 3],
       [2, 4]])

In [108]:
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [109]:
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [110]:
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [112]:
# error! inner dimensions must match
A.dot(B.T)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [ ]:
np.linalg.det(A)

In [ ]:
np.linalg.inv(A)

In [ ]:
np.linalg.inv(A).dot(A)

In [ ]:
np.trace(A)

In [ ]:
np.diag(A)

In [ ]:
np.diag([1, 4])

In [ ]:
np.linalg.eig(A)

In [ ]:
Lam, V = np.linalg.eig(A)

In [ ]:
V[:,0] * Lam[0] == A @ V[:,0]

In [ ]:
V[:,0] * Lam[0], A @ V[:,0]

In [ ]:
np.allclose(V[:,0] * Lam[0], A @ V[:,0])

In [ ]:
np.allclose(V @ np.diag(Lam), A @ V)

## Solving Linear Systems

In [ ]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [ ]:
np.linalg.solve(A, b)

In [ ]:
# don't do this
np.linalg.inv(A).dot(b)

## Generating Data

In [ ]:
np.zeros((2, 3))

In [ ]:
np.ones((2, 3))

In [ ]:
10 * np.ones((2, 3))

In [ ]:
np.eye(3)

In [ ]:
np.random.random()

In [ ]:
np.random.random((2, 3))

In [ ]:
np.random.randn(2, 3)

In [ ]:
R = np.random.randn(10000)

In [ ]:
R.mean()

In [ ]:
np.mean(R)

In [ ]:
R.var()

In [ ]:
R = np.random.randn(10000, 3)

In [ ]:
R.mean(axis=0)

In [ ]:
R.mean(axis=1).shape

In [ ]:
np.cov(R).shape

In [ ]:
np.cov(R.T)

In [ ]:
np.cov(R, rowvar=False)

In [ ]:
np.random.randint(0, 10, size=(3, 3))

In [ ]:
np.random.choice(10, size=(3, 3))